# Generated by Django 5.2.3 on 2025-07-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negozi', '0002_remove_negozio_direttore_negozio_direttore_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilitaprodotto',
            name='corridoio',
        ),
        migrations.RemoveField(
            model_name='disponibilitaprodotto',
            name='scaffale',
        ),
        migrations.RemoveField(
            model_name='negozio',
            name='latitudine',
        ),
        migrations.RemoveField(
            model_name='negozio',
            name='longitudine',
        ),
    ]
