# Generated by Django 5.2.3 on 2025-07-10 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negozi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('eta', models.PositiveIntegerField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('negozio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipendenti', to='negozi.negozio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dipendente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
            },
        ),
    ]
