# Generated by Django 5.2.3 on 2025-07-07 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negozi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessaggioForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('chat', 'Messaggio Chat'), ('recensione', 'Recensione Negozio'), ('ricetta', 'Ricetta')], default='chat', max_length=20)),
                ('contenuto', models.TextField(help_text='Contenuto del messaggio')),
                ('stelle', models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], help_text='Valutazione stelle', null=True)),
                ('nome_ricetta', models.CharField(blank=True, help_text='Nome della ricetta', max_length=200, null=True)),
                ('ingredienti_ricetta', models.JSONField(blank=True, default=list, help_text='Lista ingredienti con prodotti', null=True)),
                ('note_ricetta', models.TextField(blank=True, help_text='Note aggiuntive per la ricetta', null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_forum', to=settings.AUTH_USER_MODEL)),
                ('negozio_recensito', models.ForeignKey(blank=True, help_text='Negozio recensito', null=True, on_delete=django.db.models.deletion.CASCADE, to='negozi.negozio')),
            ],
            options={
                'verbose_name': 'Messaggio Forum',
                'verbose_name_plural': 'Messaggi Forum',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
