# Generated by Django 5.2.3 on 2025-07-04 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negozi', '0001_initial'),
        ('prodotti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, help_text='Data di creazione del carrello')),
                ('data_modifica', models.DateTimeField(auto_now=True, help_text="Data dell'ultima modifica al carrello")),
                ('negozio', models.ForeignKey(blank=True, help_text='Negozio di riferimento per questo carrello', null=True, on_delete=django.db.models.deletion.SET_NULL, to='negozi.negozio')),
                ('utente', models.OneToOneField(help_text='Utente proprietario del carrello', on_delete=django.db.models.deletion.CASCADE, related_name='carrello', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrello',
                'verbose_name_plural': 'Carrelli',
            },
        ),
        migrations.CreateModel(
            name='ElementoCarrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1, help_text='Quantità del prodotto nel carrello')),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, help_text="Prezzo unitario al momento dell'aggiunta al carrello", max_digits=8)),
                ('sconto_applicato', models.DecimalField(decimal_places=2, default=0, help_text="Percentuale di sconto applicata al momento dell'aggiunta", max_digits=5)),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True, help_text='Data di aggiunta del prodotto al carrello')),
                ('data_modifica', models.DateTimeField(auto_now=True, help_text="Data dell'ultima modifica alla quantità")),
                ('carrello', models.ForeignKey(help_text='Carrello di appartenenza', on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='carrello.carrello')),
                ('prodotto', models.ForeignKey(help_text='Prodotto nel carrello', on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
            ],
            options={
                'verbose_name': 'Elemento Carrello',
                'verbose_name_plural': 'Elementi Carrello',
                'ordering': ['-data_aggiunta'],
                'unique_together': {('carrello', 'prodotto')},
            },
        ),
    ]
