# Generated by Django 5.2.3 on 2025-07-08 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrello', '0001_initial'),
        ('negozi', '0001_initial'),
        ('prodotti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome e cognome', max_length=200)),
                ('email', models.EmailField(help_text='Email per conferma ordine', max_length=254)),
                ('telefono', models.CharField(help_text='Numero di telefono', max_length=20)),
                ('indirizzo', models.CharField(help_text='Indirizzo di consegna', max_length=300)),
                ('citta', models.CharField(help_text='Città', max_length=100)),
                ('cap', models.CharField(help_text='Codice postale', max_length=10)),
                ('provincia', models.CharField(help_text='Provincia', max_length=2)),
                ('note_consegna', models.TextField(blank=True, help_text='Note per la consegna', null=True)),
                ('subtotale', models.DecimalField(decimal_places=2, help_text='Subtotale prodotti', max_digits=8)),
                ('spese_spedizione', models.DecimalField(decimal_places=2, help_text='Costo spedizione', max_digits=8)),
                ('totale_finale', models.DecimalField(decimal_places=2, help_text='Totale finale', max_digits=8)),
                ('stato', models.CharField(choices=[('confermato', 'Confermato'), ('in_preparazione', 'In Preparazione'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], default='confermato', max_length=20)),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('codice_ordine', models.CharField(help_text='Codice univoco ordine', max_length=20, unique=True)),
                ('negozio', models.ForeignKey(help_text="Negozio dal quale è stato effettuato l'ordine", null=True, on_delete=django.db.models.deletion.SET_NULL, to='negozi.negozio')),
                ('utente', models.ForeignKey(help_text="Utente che ha effettuato l'ordine", on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_ordine'],
            },
        ),
        migrations.CreateModel(
            name='ElementoOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(help_text='Quantità ordinata')),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, help_text="Prezzo unitario al momento dell'ordine", max_digits=8)),
                ('sconto_applicato', models.DecimalField(decimal_places=2, default=0, help_text="Sconto applicato al momento dell'ordine", max_digits=5)),
                ('prodotto', models.ForeignKey(help_text='Prodotto ordinato', on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
                ('ordine', models.ForeignKey(help_text='Ordine di appartenenza', on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='carrello.ordine')),
            ],
            options={
                'verbose_name': 'Elemento Ordine',
                'verbose_name_plural': 'Elementi Ordine',
            },
        ),
    ]
