# Generated by Django 5.2.3 on 2025-07-01 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome della lista (es: 'Spesa settimanale', 'Cena romantica')", max_length=100)),
                ('descrizione', models.TextField(blank=True, help_text='Descrizione opzionale della lista', null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True, help_text='Data di creazione della lista')),
                ('data_modifica', models.DateTimeField(auto_now=True, help_text="Data dell'ultima modifica")),
                ('completata', models.BooleanField(default=False, help_text='Indica se la lista è stata completata/acquistata')),
                ('condivisa', models.BooleanField(default=False, help_text='Indica se la lista può essere condivisa con altri utenti')),
                ('utente', models.ForeignKey(help_text='Utente proprietario della lista', on_delete=django.db.models.deletion.CASCADE, related_name='liste_spesa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista della Spesa',
                'verbose_name_plural': 'Liste della Spesa',
                'ordering': ['-data_modifica', '-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='ListaCondivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permessi', models.CharField(choices=[('lettura', 'Solo Lettura'), ('modifica', 'Lettura e Modifica'), ('completo', 'Controllo Completo')], default='lettura', help_text="Livello di permessi per l'utente", max_length=20)),
                ('data_condivisione', models.DateTimeField(auto_now_add=True)),
                ('utente_condiviso', models.ForeignKey(help_text='Utente con cui è condivisa la lista', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condivisioni', to='utenti.listaspesa')),
            ],
            options={
                'verbose_name': 'Lista Condivisa',
                'verbose_name_plural': 'Liste Condivise',
                'unique_together': {('lista', 'utente_condiviso')},
            },
        ),
        migrations.CreateModel(
            name='ElementoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1, help_text='Quantità del prodotto da acquistare')),
                ('acquisito', models.BooleanField(default=False, help_text='Indica se il prodotto è già stato acquistato')),
                ('note', models.TextField(blank=True, help_text="Note aggiuntive per il prodotto (es: 'marca specifica', 'se in offerta')", null=True)),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True, help_text='Data di aggiunta del prodotto alla lista')),
                ('priorita', models.IntegerField(choices=[(0, 'Normale'), (1, 'Alta'), (2, 'Urgente')], default=0, help_text='Priorità di acquisto del prodotto')),
                ('prodotto', models.ForeignKey(help_text='Prodotto da acquistare', on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
                ('lista', models.ForeignKey(help_text='Lista di appartenenza', on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='utenti.listaspesa')),
            ],
            options={
                'verbose_name': 'Elemento Lista',
                'verbose_name_plural': 'Elementi Lista',
                'ordering': ['-priorita', 'data_aggiunta'],
                'unique_together': {('lista', 'prodotto')},
            },
        ),
    ]
