# Generated by Django 5.2.3 on 2025-07-02 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negozi', '0001_initial'),
        ('utenti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudine', models.DecimalField(blank=True, decimal_places=7, help_text="Latitudine della posizione dell'utente", max_digits=10, null=True)),
                ('longitudine', models.DecimalField(blank=True, decimal_places=7, help_text="Longitudine della posizione dell'utente", max_digits=10, null=True)),
                ('citta', models.CharField(blank=True, help_text="Città dell'utente", max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, help_text="Provincia dell'utente", max_length=2, null=True)),
                ('raggio_ricerca_km', models.PositiveIntegerField(default=20, help_text='Raggio di ricerca in km per negozi vicini')),
                ('condividi_posizione', models.BooleanField(default=True, help_text='Consenso a condividere la posizione per suggerimenti')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('negozio_preferito', models.ForeignKey(blank=True, help_text="Negozio preferito dell'utente", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti_preferiti', to='negozi.negozio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo Utente',
                'verbose_name_plural': 'Profili Utenti',
            },
        ),
    ]
