# Generated by Django 5.2.3 on 2025-07-08 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0001_initial'),
        ('utenti', '0003_remove_profiloutente_latitudine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementolista',
            name='acquisito',
        ),
        migrations.AlterField(
            model_name='elementolista',
            name='data_aggiunta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='elementolista',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='utenti.listaspesa'),
        ),
        migrations.AlterField(
            model_name='elementolista',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementolista',
            name='priorita',
            field=models.IntegerField(choices=[(0, 'Normale'), (1, 'Alta'), (2, 'Urgente')], default=0),
        ),
        migrations.AlterField(
            model_name='elementolista',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto'),
        ),
        migrations.AlterField(
            model_name='elementolista',
            name='quantita',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
