# Generated by Django 5.2.3 on 2025-07-12 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negozi', '0002_remove_negozio_direttore_negozio_direttore_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('eta', models.PositiveIntegerField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('livello_accesso', models.CharField(choices=[('direttore_generale', 'Direttore Generale'), ('vice_direttore', 'Vice Direttore'), ('direttore_negozio', 'Direttore di Negozio'), ('manager_area', 'Manager di Area')], default='direttore_negozio', max_length=20)),
                ('data_assunzione', models.DateField(blank=True, null=True)),
                ('stipendio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note_direzione', models.TextField(blank=True, help_text='Note dalla direzione generale')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('negozi_supervisionati', models.ManyToManyField(blank=True, help_text='Negozi aggiuntivi sotto supervisione', related_name='dirigenti_area', to='negozi.negozio')),
                ('negozio_principale', models.ForeignKey(help_text='Negozio principale che dirige', on_delete=django.db.models.deletion.CASCADE, related_name='dirigente_responsabile', to='negozi.negozio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dirigente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirigente',
                'verbose_name_plural': 'Dirigenti',
                'ordering': ['livello_accesso', 'cognome', 'nome'],
            },
        ),
    ]
