# Generated by Django 5.2.3 on 2025-06-30 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('latticini', 'Latticini'), ('carne', 'Carne e Pesce'), ('verdura', 'Verdura'), ('frutta', 'Frutta'), ('conserve', 'Conserve e Sottoli'), ('pasta', 'Pasta e Riso'), ('olio', 'Olio e Condimenti'), ('spezie', 'Spezie e Aromi'), ('proteine', 'Proteine Vegetali'), ('snack', 'Snack e Merende'), ('cereali', 'Cereali e Derivati'), ('bevande', 'Bevande'), ('dolci', 'Dolci e Snack'), ('surgelati', 'Surgelati'), ('altro', 'Altro')], max_length=50)),
                ('descrizione', models.TextField(blank=True)),
                ('codice_a_barre', models.CharField(max_length=50, unique=True)),
                ('peso', models.CharField(max_length=50)),
                ('data_scadenza', models.DateField()),
                ('foto', models.ImageField(blank=True, upload_to='prodotti/')),
                ('valori_nutrizionali', models.JSONField(blank=True, default=dict)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ingredienti', models.TextField(blank=True)),
                ('numero_recensioni', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.CharField(max_length=20, unique=True)),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('confermato', 'Confermato'), ('preparazione', 'In Preparazione'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], default='in_attesa', max_length=20)),
                ('nome_fatturazione', models.CharField(max_length=100)),
                ('cognome_fatturazione', models.CharField(max_length=100)),
                ('email_fatturazione', models.EmailField(max_length=254)),
                ('telefono_fatturazione', models.CharField(max_length=20)),
                ('indirizzo_fatturazione', models.CharField(max_length=200)),
                ('citta_fatturazione', models.CharField(max_length=100)),
                ('cap_fatturazione', models.CharField(max_length=10)),
                ('provincia_fatturazione', models.CharField(max_length=50)),
                ('spedizione_diversa', models.BooleanField(default=False)),
                ('nome_spedizione', models.CharField(blank=True, max_length=100)),
                ('cognome_spedizione', models.CharField(blank=True, max_length=100)),
                ('indirizzo_spedizione', models.CharField(blank=True, max_length=200)),
                ('citta_spedizione', models.CharField(blank=True, max_length=100)),
                ('cap_spedizione', models.CharField(blank=True, max_length=10)),
                ('provincia_spedizione', models.CharField(blank=True, max_length=50)),
                ('metodo_pagamento', models.CharField(choices=[('carta', 'Carta di Credito'), ('paypal', 'PayPal'), ('contrassegno', 'Contrassegno'), ('bonifico', 'Bonifico Bancario')], max_length=20)),
                ('subtotale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sconto_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spese_spedizione', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_ordine'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sconto_applicato', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subtotale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
            ],
            options={
                'unique_together': {('ordine', 'prodotto')},
            },
        ),
    ]
