# Generated by Django 5.2.3 on 2025-07-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negozi', '0001_initial'),
        ('prodotti', '0003_alter_prodotto_negozio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='negozio',
            field=models.ForeignKey(blank=True, help_text='Negozio specifico per questo prodotto. Lascia vuoto se il prodotto è disponibile in tutti i negozi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodotti_specifici', to='negozi.negozio'),
        ),
    ]
