# Generated by Django 5.2.3 on 2025-07-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negozi', '0001_initial'),
        ('prodotti', '0004_alter_prodotto_negozio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='negozio',
        ),
        migrations.AddField(
            model_name='prodotto',
            name='negozi',
            field=models.ManyToManyField(blank=True, help_text='Negozi dove questo prodotto è disponibile. Lascia vuoto per renderlo disponibile in tutti i negozi.', related_name='prodotti_disponibili', to='negozi.negozio'),
        ),
    ]
