# Generated by Django 5.2.3 on 2025-07-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0005_remove_prodotto_negozio_prodotto_negozi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(choices=[('latticini', 'Latticini'), ('carne', 'Carne e Pesce'), ('fresco', 'Fresco (Pesce e Frutti di Mare)'), ('verdura', 'Verdura'), ('frutta', 'Frutta'), ('conserve', 'Conserve e Sottoli'), ('pasta', 'Pasta e Riso'), ('olio', 'Olio e Condimenti'), ('spezie', 'Spezie e Aromi'), ('proteine', 'Proteine Vegetali'), ('snack', 'Snack e Merende'), ('cereali', 'Cereali e Derivati'), ('bevande', 'Bevande'), ('dolci', 'Dolci e Snack'), ('surgelati', 'Surgelati'), ('altro', 'Altro')], max_length=50),
        ),
    ]
