# Generated by Django 5.2.3 on 2025-07-13 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0006_alter_prodotto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='sconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
